name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: "Setup Gradle Environment"
        uses: gradle/actions/setup-gradle@v4
        with:
          validate-wrappers: true
          gradle-version: wrapper
          cache-disabled: false

      - name: Build artifacts
        run: ./gradlew build -Pbuild.release=true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: build/libs/*.jar
